# Generated by Django 3.0.4 on 2020-03-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearcode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cditem',
            name='last_map_date',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp set to the date of the last mapping. Used to track mapping status.', null=True),
        ),
        migrations.AddField(
            model_name='cditem',
            name='type',
            field=models.IntegerField(choices=[(1, 'Definition'), (2, 'Harvest')], db_index=True, help_text='Type of CDitem', null=True),
        ),
    ]
