# Generated by Django 3.0.4 on 2020-03-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearcode', '0002_auto_20200317_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='cditem',
            name='is_mappable',
            field=models.BooleanField(db_index=True, default=False, help_text='When set to True (Yes), this field indicates that this CDitem can be processed by MineCode'),
        ),
    ]
