# Generated by Django 3.0.4 on 2020-03-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearcode', '0003_cditem_is_mappable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cditem',
            name='is_mappable',
        ),
        migrations.RemoveField(
            model_name='cditem',
            name='type',
        ),
        migrations.AddField(
            model_name='cditem',
            name='map_error',
            field=models.TextField(blank=True, help_text='Mapping errors messages. When present this means the mapping failed.', null=True),
        ),
    ]
